spring.application.name=tovarika

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tovarika}
spring.datasource.username=${DB_USERNAME:tovarika}
spring.datasource.password=${DB_PASSWORD:tovarika}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.servlet.multipart.max-file-size=${MAX_IMAGE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_IMAGE_SIZE:20MB}

tovarika.storage.minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
tovarika.storage.minio.access-key=${MINIO_ACCESS_KEY:tovarika}
tovarika.storage.minio.secret-key=${MINIO_SECRET_KEY:tovarika-secret}
tovarika.storage.minio.bucket=${MINIO_BUCKET:user-images}
tovarika.storage.minio.initialize-bucket=${MINIO_INITIALIZE_BUCKET:true}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/openapi/tovarika-openapi.yaml
springdoc.swagger-ui.disable-swagger-default-url=true
