package com.tovarika.tech.auth.application;

public enum AuthErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_REQUIRED,
    ACCESS_TOKEN_INVALID,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_REGISTERED,
    PASSWORD_RESET_TOKEN_INVALID,
    SESSION_NOT_FOUND,
    SESSION_REVOKED,
    REFRESH_TOKEN_REUSE_DETECTED,
    OAUTH_STATE_INVALID,
    OAUTH_PROVIDER_ERROR,
    FORBIDDEN,
    RATE_LIMITED,
    INTERNAL_ERROR
}
